Lesson1 task3
Talaybekovna/KotlinSprint pull request #3
Opened 2024-06-06 20:38 UTC by Talaybekovna

2024-06-09 07:11 UTC, ievetrovdev requested changes

2024-06-09 07:11 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +    var hour: String
А почему не сделать таким образом?) `var hour = "09"`

2024-06-09 07:11 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +    var minute: String
И здесь также

2024-06-09 11:03 UTC, Talaybekovna commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +    var hour: String
Понято принято

2024-06-10 07:35 UTC, ievetrovdev approved these changes

2024-06-10 20:03 UTC, merged