Lesson1 task4
Talaybekovna/KotlinSprint pull request #4
Opened 2024-06-06 20:52 UTC by Talaybekovna

2024-06-09 07:15 UTC, ievetrovdev requested changes

2024-06-09 07:15 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task4.kt
> +    val aged = 27
Можно удалить эту переменную, выше она уже объявлена. В остальном все отлично)

2024-06-09 11:08 UTC, Talaybekovna commented on src/main/kotlin/lesson_1/lesson1_task4.kt
> +    val aged = 27
Буду внимательнее

2024-06-10 07:35 UTC, ievetrovdev approved these changes

2024-06-10 20:04 UTC, merged