Lesson1 task5
Talaybekovna/KotlinSprint pull request #5
Opened 2024-06-06 21:06 UTC by Talaybekovna

2024-06-09 07:17 UTC, ievetrovdev requested changes

2024-06-09 07:17 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    val hours = totalSeconds / 60 / 60
Чтобы снизить риск ошибок, предлагаю все “голые” числа вынести в константу. Кроме того это [магические числа](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

Нейминг констант отличен от обычных переменных. В [документации по ссылке](https://developer.android.com/kotlin/style-guide#constant_names) есть более полное описание стайл гайда

2024-06-09 07:17 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    print("0$hours:$minutes:0$seconds")
Так как это 5 задача ("со звездочкой") не по уровню урока, то предлагаю использовать более элегантное решение). (может потребовать дополнительного ресерча). Для корректного вывода нуля вначале попробуй посмотреть в сторону String.format().

2024-06-09 11:26 UTC, Talaybekovna commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    print("0$hours:$minutes:0$seconds")
Очень нужная информация. Спасибо.

2024-06-09 11:26 UTC, Talaybekovna commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    val hours = totalSeconds / 60 / 60
Очень нужная информация. Спасибо.

2024-06-11 04:56 UTC, ievetrovdev approved these changes

2024-06-12 11:51 UTC, merged