KS-2-2 calculate arrival time.
Talaybekovna/KotlinSprint pull request #8
Opened 2024-06-08 17:13 UTC by Talaybekovna

updated: KS-2-3.

2024-06-10 20:36 UTC, ievetrovdev requested changes

2024-06-10 20:36 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task3.kt
> +    println("$arrivalTimeInHours:$arrivalTimeInMinutes")
Вывод должен быть с ведущими нулями

2024-06-10 20:37 UTC, ievetrovdev commented
Наименование ПР не верное

2024-06-12 19:02 UTC, ievetrovdev commented
Почему в названии KS-2-2, если задача 3 ?

2024-06-12 19:03 UTC, ievetrovdev requested changes
Наименование ПР не верное, KS-2-2, это задание 3

2024-06-12 19:18 UTC, Talaybekovna commented
> Наименование ПР не верное, KS-2-2, это задание 3

Исправлено

2024-06-12 19:30 UTC, ievetrovdev approved these changes
Все верно!

2024-06-12 19:45 UTC, merged