KS-2-4 calculate baff.
Talaybekovna/KotlinSprint pull request #9
Opened 2024-06-08 17:13 UTC by Talaybekovna

2024-06-10 20:39 UTC, ievetrovdev requested changes

2024-06-10 20:39 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +const val BAFF = 0.2
Это не константа, и нужно задать как 20, так как в условии так указано.

2024-06-12 11:51 UTC, Talaybekovna commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +const val BAFF = 0.2
Исправляю

2024-06-12 19:04 UTC, ievetrovdev approved these changes
Все верно!

2024-06-12 19:18 UTC, merged